name: samsung
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - python=3.8.13
  - pytorch=1.11.0
  - torchvision=0.12.0
  - pip:
    - einops==0.4.1
    - torchsummary==1.5.1
    - wandb==0.12.17